sudo: false
services:
  - postgresql
language: node_js
node_js:
  - stable
addons:
  postgresql: "10"
env:
  global:
    - NODE_ENV=development
    - SECRETKEY=BAHATIROBBEN
    - PG_HOST=localhost
    - PG_URL=postgresql://admin:bahati@localhost/proplite
    - PG_USER=admin
    - PG_DATABASE=proplite
    - PG_PASSWORD=1234567890
    - PG_PORT=5432
before_script:
  - psql -c 'create database proplite;' -U postgres
  - psql -c "CREATE USER admin WITH PASSWORD 'bahati';" -U postgres
script:
  npm test
after_success: npm run coverage
